export const ActionTypes = {
  SET_PRODUCTS: "SET_PRODUCTS",
  SELECTED_PRODUCT: "SELECTED_PRODUCT",
  REMOVE_SELECTED_PRODUCT: "REMOVE_SELECTED_PRODUCT",
  SET_GRID: "SET_GRID",
  SET_QUERY: "SET_QUERY",
  SET_BRANDS: "SET_BRANDS",
  SET_CATEGORIES: "SET_CATEGORIES",
  SET_FILTERS: "SET_FILTERS",
  SET_CART: "SET_CART",
};
